/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: tamminen (https://sketchfab.com/tamminen)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/flaming-orb-d7f8cda1e8ae4e458cd674bc18db672c
title: Flaming orb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
    const { nodes, materials, animations } = useGLTF('./models/flaming_orb.glb')
    const { actions } = useAnimations(animations, group)
    console.log(actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Icosphere002_0">
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Icosphere001_1">
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Scene_-_Root']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/flaming_orb.glb')
