/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/incandescent-helix-f59bfbbe2d7a4c5dba7c5712114ee53c
title: Incandescent Helix
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/incandescent_helix.glb')
    const { actions } = useAnimations(animations, group)
    useEffect(() => { actions.Animation.play(); });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Torus_Knot_12_x_27_0">
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.material} />
              </group>
              <group name="Torus_Knot_7_x_41_1">
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material_1} />
              </group>
              <group name="Circle_2" scale={1.5} />
              <group name="Sphere_3" scale={0.11}>
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.material_2} />
              </group>
              <group name="Sphere001_4" scale={0.1}>
                <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.material_3} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/incandescent_helix.glb')
