/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/magic-furball-02cf1a48f70f4fedaf8ecde1f0dfd925
title: Magic Furball
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/magic_furball.glb')
    const { actions } = useAnimations(animations, group)
    useEffect(() => { actions.Object_0.play(); });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="010131fbfb5b408aa296a3e42741c177abccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group name="Object_4" />
                <group name="Object_5">
                  <group name="MorphMainGroup">
                    <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={materials.Icosphere} morphTargetDictionary={nodes.Icosphere.morphTargetDictionary} morphTargetInfluences={nodes.Icosphere.morphTargetInfluences} />
                    <mesh name="Icosphere_1" geometry={nodes.Icosphere_1.geometry} material={materials.Icosphere} morphTargetDictionary={nodes.Icosphere_1.morphTargetDictionary} morphTargetInfluences={nodes.Icosphere_1.morphTargetInfluences} />
                    <mesh name="Icosphere_2" geometry={nodes.Icosphere_2.geometry} material={materials.Icosphere} morphTargetDictionary={nodes.Icosphere_2.morphTargetDictionary} morphTargetInfluences={nodes.Icosphere_2.morphTargetInfluences} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/magic_furball.glb')
