/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/helix-wave3-9cc9a6dad7854aeb9170a1e75524b2c6
title: Helix Wave³
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
    const { nodes, materials, animations } = useGLTF("/models/scene.gltf")
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube_0" position={[1, -2, 0]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Material} />
              </group>
              <group name="Circle_1" position={[-1, -2, 0]} />
              <group name="Circle001_2" position={[-3, 0, 0]} />
              <group name="Circle002_3" position={[-1, 4, 0]} />
              <group name="Circle003_4" position={[3, 0, 0]} />
              <group name="Cube001_5" position={[3, 2, 0]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Material} />
              </group>
              <group name="Circle005_6" position={[3, 0, 0]} />
              <group name="Circle006_7" position={[1, -2, 0]} />
              <group name="Circle007_8" position={[-3, 0, 0]} />
              <group name="Circle008_9" position={[1, 4, 0]} />
              <group name="Cube002_10" position={[-1, 4, 0]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Material} />
              </group>
              <group name="Circle010_11" position={[1, 4, 0]} />
              <group name="Circle011_12" position={[3, 2, 0]} />
              <group name="Circle012_13" position={[1, -2, 0]} />
              <group name="Circle013_14" position={[-3, 2, 0]} />
              <group name="Cube003_15" position={[-3, 0, 0]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Material} />
              </group>
              <group name="Circle015_16" position={[-3, 2, 0]} />
              <group name="Circle016_17" position={[-1, 4, 0]} />
              <group name="Circle017_18" position={[3, 2, 0]} />
              <group name="Circle018_19" position={[-1, -2, 0]} />
              <group name="Cube004_25" position={[1, -2, -2]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Material} />
              </group>
              <group name="Circle021_26" position={[-1, -2, -2]} />
              <group name="Circle022_27" position={[-3, 0, -2]} />
              <group name="Circle023_28" position={[-1, 4, -2]} />
              <group name="Circle024_29" position={[3, 0, -2]} />
              <group name="Cube005_30" position={[3, 2, -2]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Material} />
              </group>
              <group name="Circle026_31" position={[3, 0, -2]} />
              <group name="Circle027_32" position={[1, -2, -2]} />
              <group name="Circle028_33" position={[-3, 0, -2]} />
              <group name="Circle029_34" position={[1, 4, -2]} />
              <group name="Cube006_35" position={[-1, 4, -2]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.Material} />
              </group>
              <group name="Circle031_36" position={[1, 4, -2]} />
              <group name="Circle032_37" position={[3, 2, -2]} />
              <group name="Circle033_38" position={[1, -2, -2]} />
              <group name="Circle034_39" position={[-3, 2, -2]} />
              <group name="Cube007_40" position={[-3, 0, -2]}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.Material} />
              </group>
              <group name="Circle036_41" position={[-3, 2, -2]} />
              <group name="Circle037_42" position={[-1, 4, -2]} />
              <group name="Circle038_43" position={[3, 2, -2]} />
              <group name="Circle039_44" position={[-1, -2, -2]} />
              <group name="Cube008_50" position={[1, -2, -4]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.Material} />
              </group>
              <group name="Circle042_51" position={[-1, -2, -4]} />
              <group name="Circle043_52" position={[-3, 0, -4]} />
              <group name="Circle044_53" position={[-1, 4, -4]} />
              <group name="Circle045_54" position={[3, 0, -4]} />
              <group name="Cube009_55" position={[3, 2, -4]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.Material} />
              </group>
              <group name="Circle047_56" position={[3, 0, -4]} />
              <group name="Circle048_57" position={[1, -2, -4]} />
              <group name="Circle049_58" position={[-3, 0, -4]} />
              <group name="Circle050_59" position={[1, 4, -4]} />
              <group name="Cube010_60" position={[-1, 4, -4]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.Material} />
              </group>
              <group name="Circle052_61" position={[1, 4, -4]} />
              <group name="Circle053_62" position={[3, 2, -4]} />
              <group name="Circle054_63" position={[1, -2, -4]} />
              <group name="Circle055_64" position={[-3, 2, -4]} />
              <group name="Cube011_65" position={[-3, 0, -4]}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.Material} />
              </group>
              <group name="Circle057_66" position={[-3, 2, -4]} />
              <group name="Circle058_67" position={[-1, 4, -4]} />
              <group name="Circle059_68" position={[3, 2, -4]} />
              <group name="Circle060_69" position={[-1, -2, -4]} />
              <group name="Cube012_75" position={[1, -2, -6]}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.Material} />
              </group>
              <group name="Circle063_76" position={[-1, -2, -6]} />
              <group name="Circle064_77" position={[-3, 0, -6]} />
              <group name="Circle065_78" position={[-1, 4, -6]} />
              <group name="Circle066_79" position={[3, 0, -6]} />
              <group name="Cube013_80" position={[3, 2, -6]}>
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.Material} />
              </group>
              <group name="Circle068_81" position={[3, 0, -6]} />
              <group name="Circle069_82" position={[1, -2, -6]} />
              <group name="Circle070_83" position={[-3, 0, -6]} />
              <group name="Circle071_84" position={[1, 4, -6]} />
              <group name="Cube014_85" position={[-1, 4, -6]}>
                <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.Material} />
              </group>
              <group name="Circle073_86" position={[1, 4, -6]} />
              <group name="Circle074_87" position={[3, 2, -6]} />
              <group name="Circle075_88" position={[1, -2, -6]} />
              <group name="Circle076_89" position={[-3, 2, -6]} />
              <group name="Cube015_90" position={[-3, 0, -6]}>
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.Material} />
              </group>
              <group name="Circle078_91" position={[-3, 2, -6]} />
              <group name="Circle079_92" position={[-1, 4, -6]} />
              <group name="Circle080_93" position={[3, 2, -6]} />
              <group name="Circle081_94" position={[-1, -2, -6]} />
              <group name="Cube016_100" position={[1, -2, -8]}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.Material} />
              </group>
              <group name="Circle084_101" position={[-1, -2, -8]} />
              <group name="Circle085_102" position={[-3, 0, -8]} />
              <group name="Circle086_103" position={[-1, 4, -8]} />
              <group name="Circle087_104" position={[3, 0, -8]} />
              <group name="Cube017_105" position={[3, 2, -8]}>
                <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.Material} />
              </group>
              <group name="Circle089_106" position={[3, 0, -8]} />
              <group name="Circle090_107" position={[1, -2, -8]} />
              <group name="Circle091_108" position={[-3, 0, -8]} />
              <group name="Circle092_109" position={[1, 4, -8]} />
              <group name="Cube018_110" position={[-1, 4, -8]}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.Material} />
              </group>
              <group name="Circle094_111" position={[1, 4, -8]} />
              <group name="Circle095_112" position={[3, 2, -8]} />
              <group name="Circle096_113" position={[1, -2, -8]} />
              <group name="Circle097_114" position={[-3, 2, -8]} />
              <group name="Cube019_115" position={[-3, 0, -8]}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.Material} />
              </group>
              <group name="Circle099_116" position={[-3, 2, -8]} />
              <group name="Circle100_117" position={[-1, 4, -8]} />
              <group name="Circle101_118" position={[3, 2, -8]} />
              <group name="Circle102_119" position={[-1, -2, -8]} />
              <group name="Cube020_125" position={[1, -2, -10]}>
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.Material} />
              </group>
              <group name="Circle105_126" position={[-1, -2, -10]} />
              <group name="Circle106_127" position={[-3, 0, -10]} />
              <group name="Circle107_128" position={[-1, 4, -10]} />
              <group name="Circle108_129" position={[3, 0, -10]} />
              <group name="Cube021_130" position={[3, 2, -10]}>
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.Material} />
              </group>
              <group name="Circle110_131" position={[3, 0, -10]} />
              <group name="Circle111_132" position={[1, -2, -10]} />
              <group name="Circle112_133" position={[-3, 0, -10]} />
              <group name="Circle113_134" position={[1, 4, -10]} />
              <group name="Cube022_135" position={[-1, 4, -10]}>
                <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.Material} />
              </group>
              <group name="Circle115_136" position={[1, 4, -10]} />
              <group name="Circle116_137" position={[3, 2, -10]} />
              <group name="Circle117_138" position={[1, -2, -10]} />
              <group name="Circle118_139" position={[-3, 2, -10]} />
              <group name="Cube023_140" position={[-3, 0, -10]}>
                <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.Material} />
              </group>
              <group name="Circle120_141" position={[-3, 2, -10]} />
              <group name="Circle121_142" position={[-1, 4, -10]} />
              <group name="Circle122_143" position={[3, 2, -10]} />
              <group name="Circle123_144" position={[-1, -2, -10]} />
              <group name="Cube024_150" position={[1, -2, -12]}>
                <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.Material} />
              </group>
              <group name="Circle126_151" position={[-1, -2, -12]} />
              <group name="Circle127_152" position={[-3, 0, -12]} />
              <group name="Circle128_153" position={[-1, 4, -12]} />
              <group name="Circle129_154" position={[3, 0, -12]} />
              <group name="Cube025_155" position={[3, 2, -12]}>
                <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.Material} />
              </group>
              <group name="Circle131_156" position={[3, 0, -12]} />
              <group name="Circle132_157" position={[1, -2, -12]} />
              <group name="Circle133_158" position={[-3, 0, -12]} />
              <group name="Circle134_159" position={[1, 4, -12]} />
              <group name="Cube026_160" position={[-1, 4, -12]}>
                <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.Material} />
              </group>
              <group name="Circle136_161" position={[1, 4, -12]} />
              <group name="Circle137_162" position={[3, 2, -12]} />
              <group name="Circle138_163" position={[1, -2, -12]} />
              <group name="Circle139_164" position={[-3, 2, -12]} />
              <group name="Cube027_165" position={[-3, 0, -12]}>
                <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.Material} />
              </group>
              <group name="Circle141_166" position={[-3, 2, -12]} />
              <group name="Circle142_167" position={[-1, 4, -12]} />
              <group name="Circle143_168" position={[3, 2, -12]} />
              <group name="Circle144_169" position={[-1, -2, -12]} />
              <group name="Cube028_175" position={[1, -2, -14]}>
                <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.Material} />
              </group>
              <group name="Circle147_176" position={[-1, -2, -14]} />
              <group name="Circle148_177" position={[-3, 0, -14]} />
              <group name="Circle149_178" position={[-1, 4, -14]} />
              <group name="Circle150_179" position={[3, 0, -14]} />
              <group name="Cube029_180" position={[3, 2, -14]}>
                <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.Material} />
              </group>
              <group name="Circle152_181" position={[3, 0, -14]} />
              <group name="Circle153_182" position={[1, -2, -14]} />
              <group name="Circle154_183" position={[-3, 0, -14]} />
              <group name="Circle155_184" position={[1, 4, -14]} />
              <group name="Cube030_185" position={[-1, 4, -14]}>
                <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.Material} />
              </group>
              <group name="Circle157_186" position={[1, 4, -14]} />
              <group name="Circle158_187" position={[3, 2, -14]} />
              <group name="Circle159_188" position={[1, -2, -14]} />
              <group name="Circle160_189" position={[-3, 2, -14]} />
              <group name="Cube031_190" position={[-3, 0, -14]}>
                <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials.Material} />
              </group>
              <group name="Circle162_191" position={[-3, 2, -14]} />
              <group name="Circle163_192" position={[-1, 4, -14]} />
              <group name="Circle164_193" position={[3, 2, -14]} />
              <group name="Circle165_194" position={[-1, -2, -14]} />
              <group name="Cube032_200" position={[1, -2, -16]}>
                <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials.Material} />
              </group>
              <group name="Circle168_201" position={[-1, -2, -16]} />
              <group name="Circle169_202" position={[-3, 0, -16]} />
              <group name="Circle170_203" position={[-1, 4, -16]} />
              <group name="Circle171_204" position={[3, 0, -16]} />
              <group name="Cube033_205" position={[3, 2, -16]}>
                <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.Material} />
              </group>
              <group name="Circle173_206" position={[3, 0, -16]} />
              <group name="Circle174_207" position={[1, -2, -16]} />
              <group name="Circle175_208" position={[-3, 0, -16]} />
              <group name="Circle176_209" position={[1, 4, -16]} />
              <group name="Cube034_210" position={[-1, 4, -16]}>
                <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials.Material} />
              </group>
              <group name="Circle178_211" position={[1, 4, -16]} />
              <group name="Circle179_212" position={[3, 2, -16]} />
              <group name="Circle180_213" position={[1, -2, -16]} />
              <group name="Circle181_214" position={[-3, 2, -16]} />
              <group name="Cube035_215" position={[-3, 0, -16]}>
                <mesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials.Material} />
              </group>
              <group name="Circle183_216" position={[-3, 2, -16]} />
              <group name="Circle184_217" position={[-1, 4, -16]} />
              <group name="Circle185_218" position={[3, 2, -16]} />
              <group name="Circle186_219" position={[-1, -2, -16]} />
              <group name="Cube036_225" position={[1, -2, -18]}>
                <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials.Material} />
              </group>
              <group name="Circle189_226" position={[-1, -2, -18]} />
              <group name="Circle190_227" position={[-3, 0, -18]} />
              <group name="Circle191_228" position={[-1, 4, -18]} />
              <group name="Circle192_229" position={[3, 0, -18]} />
              <group name="Cube037_230" position={[3, 2, -18]}>
                <mesh name="Object_226" geometry={nodes.Object_226.geometry} material={materials.Material} />
              </group>
              <group name="Circle194_231" position={[3, 0, -18]} />
              <group name="Circle195_232" position={[1, -2, -18]} />
              <group name="Circle196_233" position={[-3, 0, -18]} />
              <group name="Circle197_234" position={[1, 4, -18]} />
              <group name="Cube038_235" position={[-1, 4, -18]}>
                <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials.Material} />
              </group>
              <group name="Circle199_236" position={[1, 4, -18]} />
              <group name="Circle200_237" position={[3, 2, -18]} />
              <group name="Circle201_238" position={[1, -2, -18]} />
              <group name="Circle202_239" position={[-3, 2, -18]} />
              <group name="Cube039_240" position={[-3, 0, -18]}>
                <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials.Material} />
              </group>
              <group name="Circle204_241" position={[-3, 2, -18]} />
              <group name="Circle205_242" position={[-1, 4, -18]} />
              <group name="Circle206_243" position={[3, 2, -18]} />
              <group name="Circle207_244" position={[-1, -2, -18]} />
              <group name="Cube040_250" position={[1, -2, -20]}>
                <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials.Material} />
              </group>
              <group name="Circle210_251" position={[-1, -2, -20]} />
              <group name="Circle211_252" position={[-3, 0, -20]} />
              <group name="Circle212_253" position={[-1, 4, -20]} />
              <group name="Circle213_254" position={[3, 0, -20]} />
              <group name="Cube041_255" position={[3, 2, -20]}>
                <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials.Material} />
              </group>
              <group name="Circle215_256" position={[3, 0, -20]} />
              <group name="Circle216_257" position={[1, -2, -20]} />
              <group name="Circle217_258" position={[-3, 0, -20]} />
              <group name="Circle218_259" position={[1, 4, -20]} />
              <group name="Cube042_260" position={[-1, 4, -20]}>
                <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials.Material} />
              </group>
              <group name="Circle220_261" position={[1, 4, -20]} />
              <group name="Circle221_262" position={[3, 2, -20]} />
              <group name="Circle222_263" position={[1, -2, -20]} />
              <group name="Circle223_264" position={[-3, 2, -20]} />
              <group name="Cube043_265" position={[-3, 0, -20]}>
                <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials.Material} />
              </group>
              <group name="Circle225_266" position={[-3, 2, -20]} />
              <group name="Circle226_267" position={[-1, 4, -20]} />
              <group name="Circle227_268" position={[3, 2, -20]} />
              <group name="Circle228_269" position={[-1, -2, -20]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
